# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-21 08:10
from __future__ import unicode_literals

from django.db import migrations
import django.db.models.manager


class Migration(migrations.Migration):

    dependencies = [
        ('days', '0002_auto_20170620_0810'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='author',
            managers=[
                ('people', django.db.models.manager.Manager()),
            ],
        ),
    ]
