# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-19 07:26
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polla', '0005_publisher'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='book',
            table='books',
        ),
    ]
